### ISSUE TITLE
Artificially generate every possible instruction?

### ISSUE THREAD

**Issue by jordr** [statinf-software/tms#4]
@SlimBenAmor, do you see a nice way to generate ELF binary file(s) with a bunch of hardcoded data such as

```
0000 0001
0000 0010
0000 0011
...
```

or just random data, that we would interpret as a TEXT section, so that we can observe any diff between `tms-disasm` and `dis2000` without having to search and build benchmarks?

**Comment by SlimBenAmor** [comment]
Yes I think it is a good idea. This somehow what I did to verify `XRET` instruction and it makes sense since it is  similar to the tables ("fetch_table.h") that Gliss generates for all possible combinations of instructions. If you want I can do it. 
The only problem I can imagine, if the output of Gliss and dis2000 are not exactly the same (character by character) then we cannot use directly `diff` to compare the files and we cannot compare visually by eyes because the output will be huge if we generate every possible instruction.

**Comment by jordr** [comment]
@SlimBenAmor we're already using diff tools at this point and they work pretty well, thanks to some modifications in GLISS and an output reprocessing python script (in tms/disasm/test`. If you know of a way to generate random bytes that dis2000 will accept to deal with, that would be great and would let us test instructions extensively 🎉

**Comment by jordr** [comment]
Great thanks to @SlimBenAmor for these.
[test_all_16bit.zip](https://github.com/statinf-software/tms/files/11132995/test_all_16bit.zip)

Just need to test that we can make it work with `tms-disasm` and push it.

**Comment by jordr** [comment]
@Alex-Ralph feel free to look into this if you have some time. There is a python script in disasm/test that can help you normalize the output.

**Comment by SlimBenAmor** [comment]
There is an error with elf loader of gliss. I will debug it.
```
tms-disasm: loader.c:853: tms_loader_open: Assertion `Text.secs != NULL' failed.
```

**Comment by jordr** [comment]
Make sure you are running tms-disasm on an ELF file, not COFF @SlimBenAmor

**Comment by SlimBenAmor** [comment]
> Make sure you are running tms-disasm on an ELF file, not COFF @SlimBenAmor

you are right COFF file result in same error but I am generating ELF file. The problem was a missing program header and symbol section header. Now it should be fixed.
